<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
						->prependStylesheet($this->basePath('css/style_menu.css'))
						->prependStylesheet($this->basePath('css/style_navbar.css'))
						->prependStylesheet($this->basePath('css/style_leftsidebar.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
						->prependStylesheet($this->basePath('css/hover.css'))
						->prependStylesheet($this->basePath('css/less.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
		
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
			->prependFile($this->basePath('//cdnjs.cloudflare.com/ajax/libs/less.js/2.6.1/less.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',)); 
			
			?>

    </head>
    <body>
	<style>
	ul .navigation{
	z-index:999;
	position:absolute;
	}
	.navigation li{
	display:inline-block;
	background:#000;
	}
	</style>
		
		<div class="self_navbar row-fluid">
			<div class="logo span2"></div>
			<div class="span10">
			<div class="collapse navbar-collapse">
		<?php echo $this->navigation('navigation')->menu();?>
		
		</div>
			</div>
		</div>
		
		<div class="after_self_navbar">
		<img src="<?echo '/img/navbar-cover.svg'?>" class="svg">
		</div>
		<div class="row-fluid" style="margin-top:10px">
		<div class="leftside span2"></div>
		<div class="span10 ">
		<? echo $this->content;?>	
		</div>
		</div> 
        <?php echo $this->inlineScript() ?>
    </body>
</html>
