<div class="row">
    <div class="col col-md-12">
        <ul class="list-unstyled menu_horizont">
		<!--массив длинный и пустой -->
            <?php
			foreach ($this->menu2 as $item) : ?>
			<? if($item['name_menu']){?>
             <li class="netro2 hvr-overline-from-left">
			 <div class="bar_navy_gate" style="width:100%;background:#333"></div>
			 <a href="<?php echo $this->url('menu', ['slug' => $item['slug']]); ?>"><?php echo $item['name_menu']; ?></a>
			 
			 </li>
			<?
			}
			?> 
            <?php endforeach ?>
        </ul>
    </div>
</div>